test:
  resources:
    repo:
      url: https://github.com/pks9862728888/github-code-generator-file-storage.git
      branch: master
      temp-clone-dir: temp/github-code-generator-file-storage

mvn:
  command: mvn.cmd
