test:
  resources:
    repo:
      url: git@github.com:pks9862728888/github-code-generator-file-storage.git
      branch: master
      temp-clone-dir: temp/github-code-generator-file-storage/
    files:
      source-dir: ${test.resources.repo.temp-clone-dir}src/test/resources/test-data/
      destination-dir: src/test/resources/test-data/

command:
  mvn: mvn.cmd

logging:
  level:
    com.demo.githubcodegeneratordemo: DEBUG
